### ISSUE TITLE
need Default constructor for generated bridge classes

### ISSUE THREAD

**Issue by jasonswearingen** [Jemy191/GDBridge#9]
Hello, I am running into a weird edge case.

When rebuilding my csharp project in my IDE, the godot editor does a cold-reload, and throws this error:

```error
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.MissingMemberException: Cannot create script instance. The class 'PhantomCamera3DBridge' does not define a parameterless constructor.
     at Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectScriptInstance(IntPtr scriptPtr, IntPtr godotObject, godot_variant** args, Int32 argCount) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 146
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.MissingMemberException: Cannot create script instance. The class 'PhantomCamera3DBridge' does not define a parameterless constructor.
     at Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectScriptInstance(IntPtr scriptPtr, IntPtr godotObject, godot_variant** args, Int32 argCount) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 146
```

Not sure why the editor needs that, but it seems to be because cold-reload calls the default constructors on all .net objects.

Adding this code manually fixes the problem:

```csharp
public partial class PhantomCamera3DBridge
{
   public PhantomCamera3DBridge() : base(null){}
}
```
so, maybe this should be added to the generated code by default?

This is on Godot 4.2

**Comment by Jemy191** [comment]
Thanks I will check that. It seem to be a godot bug or some oversight.

**Comment by jasonswearingen** [comment]
oh one more thing, this only happens when the scene has the `[Tool]` attribute.  without it there is no error

**Comment by Jemy191** [comment]
The scene? Do you mean the bridge class?
Could you give me a snipet of your code?

**Comment by jasonswearingen** [comment]
The scene that I'm instancing the bridge from is a `[Tool]`.  it's something about how the Editor cold-reloads tool code.

here's an example of what i'm doing

```csharp
[SceneTree]
[Tool]
public partial class Main : Node
{
   public World World { get; set; }

   public PhantomCamera3DBridge pcamBridge { get; set; }
   public Node3D pcam { get; set; }

   // Called when the node enters the scene tree for the first time.
   public override void _Ready()
   {
      World = new();
      AddChild(World);

      var xbotCharacter = _GD.InstantiateScene<xbotCharacter>();
      this._AddChild(xbotCharacter);
      
      pcam = _.PhantomCamera3D;
      pcamBridge = new PhantomCamera3DBridge(pcam);

     }

//more code......
```

**Comment by Jemy191** [comment]
Bridge used with [Tool] class are special case. Adding a parameter less constructor to the genereted class would lead to confusion on it use. It would be best to add it manually as a partial class.
